title: Petter Kärnestad
description: Min personliga hemsida med GitHub Pages
baseurl: "" # använd "" för root, eller "/din-sajt" om du har en projekt-sida
url: "https://petterbror.github.io"
theme: minima # enkelt och snyggt standardtema
